---
- name: Provision Hetzner Server from Snapshot and Restart Docker Containers
  hosts: localhost
  gather_facts: false
  vars:
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
    server_name: "mattermost-server"
    server_type: "cpx41" # Adjust server type as needed
    snapshot_id: "167899132" # Replace with your snapshot ID
    ssh_key: "{{ lookup('env', 'SSH_KEY_NAME') }}"
    primary_ip4_name: "primary_ip-63985281"
    primary_ip6_name: "primary_ip-63985283"
  tasks:
    - name: Create Hetzner Cloud Server from Snapshot
      hetzner.hcloud.hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ server_name }}"
        server_type: "{{ server_type }}"
        image: "{{ snapshot_id }}"
        ssh_keys: "{{ ssh_key }}"
        state: present
        ipv4: "{{ primary_ip4_name }}"
        ipv6: "{{ primary_ip6_name }}"
      register: hcloud_server

    - name: Debug hcloud_server variable
      debug:
        var: hcloud_server

    - name: Remove old SSH host key
      known_hosts:
        path: /home/mahrezbh/.ssh/known_hosts
        name: "{{ hcloud_server.hcloud_server.ipv4_address }}"
        state: absent

    - name: Add new SSH host key
      shell: ssh-keyscan -H {{ hcloud_server.hcloud_server.ipv4_address }} >> /home/mahrezbh/.ssh/known_hosts
      ignore_errors: true

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ hcloud_server.hcloud_server.ipv4_address }}"
        port: 22
        delay: 20
        timeout: 600
        state: started

    - name: Verify SSH connection manually
      shell: ssh -o StrictHostKeyChecking=no root@{{ hcloud_server.hcloud_server.ipv4_address }} echo "SSH is up"

    - name: Add new server to inventory
      add_host:
        name: mattermost-server
        ansible_host: "{{ hcloud_server.hcloud_server.ipv4_address }}"
        ansible_user: root

    - name: Refresh inventory
      meta: refresh_inventory

- name: Restart Docker Containers on new server
  hosts: mattermost-server
  become: true
  tasks:
    - name: List all Docker containers
      shell: docker ps -q
      register: docker_containers

    - name: Restart all Docker containers
      shell: |
        for container in $(docker ps -q); do
          docker restart $container;
        done
      when: docker_containers.stdout != ""
